import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "<redux>/styles/Home.module.css";

import { useEffect, useState } from "react";

type Food = {
  food: string;
  eaten: boolean;
};

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [foods, setFoods] = useState<Food[]>([]);

  useEffect(() => {
    const fetchGroups = async () => {
      const res = await fetch(
        "https://smq0v7nrq9.execute-api.us-east-1.amazonaws.com/summer2023planner-stage/summer2023-food-retrieve",
        {
          method: "GET",
        }
      );
      const foods = await res.json();

      console.log("FOODS: ");
      console.log(foods);

      setFoods(foods);
    };

    fetchGroups();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Summer 2023 Planner</h1>
        <ul>
          {foods.map((food, index) => (
            <li key={index}>
              <h2>{food.food}</h2>
              {!food.eaten ? <p>먹어야 될 것</p> : <p>먹은 것</p>}
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
